global:
  scrape_interval: 10s # Default is every 1 minute.

scrape_configs:
  - job_name: 'otel-collector'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['otel-collector:9464']
    #  - targets: ['otel-collector:8888']